//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FlyCap2_MFC.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_FLYCAP2_MFC_FORM            101
#define ID_INDICATOR_EVENTS             101
#define ID_INDICATOR_CURSORINFO         102
#define ID_INDICATOR_IMAGEINFO          103
#define IDR_MAINFRAME                   128
#define IDR_BitmapTYPE                  129
#define IDR_FlyCap2MFCTYPE              130
#define IDD_LICENSE                     130
#define IDB_BITMAP_ABOUT                132
#define IDB_BITMAP_EXIT                 133
#define IDB_BITMAP_HELP                 134
#define IDB_BITMAP_SAVEAS               136
#define IDB_BITMAP_CONTROL              137
#define IDB_BITMAP_LOGO                 138
#define IDD_DIALOG_HISTOGRAM            139
#define IDD_TABPAGE_HISTOGRAM           140
#define IDD_TABPAGE_ROWCOLPLOT          142
#define IDD_DIALOG_EVENT                143
#define IDB_BITMAP_EVENT_BAD            145
#define IDB_BITMAP_EVENT_OK             146
#define IDD_DIALOG_IMG_VID_RECORD       146
#define IDD_TABPAGE_VIDEO_RECORD        150
#define IDD_TABPAGE_IMAGE_RECORD        152
#define IDC_CURSOR_GRAB                 155
#define IDI_ICON_NEW                    162
#define IDB_TOOLBAR_ENABLE              163
#define IDB_TOOLBAR_DISABLE             164
#define IDD_XMLPATH_DIALOG              165
#define IDD_PANE_VIDEO_MJPEG            166
#define IDD_PANE_VIDEO_H264             167
#define IDD_PANE_IMAGE_PXM              168
#define IDD_PANE_IMAGE_BMP              169
#define IDD_PANE_IMAGE_JPG2K            170
#define IDD_PANE_IMAGE_JPG              171
#define IDD_PANE_IMAGE_PNG              172
#define IDD_PANE_IMAGE_TIFF             173
#define IDD_DIALOG_CROSSHAIR_DIMENSION  174
#define IDC_INFOTREE                    1001
#define IDC_IMAGEAREA                   1004
#define IDC_VSCROLLBAR                  1005
#define IDC_HSCROLLBAR                  1006
#define IDC_VERSION                     1011
#define IDC_BUILD_INFO                  1012
#define IDC_BUTTON_LICENSE              1014
#define IDC_LICENSE_CONTENT             1015
#define IDC_STATIC_HISTOGRAM            1017
#define IDC_STATIC_DRAWINGAREA          1017
#define IDC_TAB_HISTOGRAM               1018
#define IDC_TABCTRL_HISTOGRAM           1018
#define IDC_GREY_CHECK                  1020
#define IDC_RED_CHECK                   1021
#define IDC_GREEN_CHECK                 1022
#define IDC_BLUE_CHECK                  1023
#define IDC_HUE_CHECK                   1024
#define IDC_SATURATION_CHECK            1025
#define IDC_LIGHTNESS_CHECK             1026
#define IDC_8_16_BIT_RADIO              1030
#define IDC_10_BIT_RADIO                1031
#define IDC_12_BIT_RADIO                1032
#define IDC_AVERAGE_CHECK               1033
#define IDC_PERCENT_EDIT                1034
#define IDC_SPIN1                       1035
#define IDC_PERCENT_SPIN                1035
#define IDC_SPIN_JPEG_COMPRESSION       1035
#define IDC_COMBO_TIMESLICE             1036
#define IDC_LIST_EVENT                  1037
#define IDC_LIST_CHANNEL                1041
#define IDC_SPIN2                       1042
#define IDC_SPIN_JPEG2K_COMPRESSION_LEVEL 1042
#define IDC_MODE_COL                    1044
#define IDC_MODE_ROW                    1045
#define IDC_DISPLAY_GREY                1046
#define IDC_DISPLAY_RED                 1047
#define IDC_DISPLAY_GREEN               1048
#define IDC_DISPLAY_BLUE                1049
#define IDC_FUNCTION_MAX                1051
#define IDC_FUNCTION_MEAN               1052
#define IDC_EDIT1                       1052
#define IDC_EDIT_JPEG_COMPRESSION       1052
#define IDC_FUNCTION_MAX3               1053
#define IDC_FUNCTION_MIN                1053
#define IDC_BUTTON1                     1053
#define IDC_BTN_SET_FRAME_RATE          1053
#define IDC_RADIO_NUM_FRAMES            1054
#define IDC_SHARPNESS_EDIT              1055
#define IDC_RADIO_NTH_FRAME             1055
#define IDC_WHITEBALANCEA_EDIT          1056
#define IDC_RADIO_NUM_SECONDS           1056
#define IDC_RADIO_NTH_SECONDS           1057
#define IDC_EDIT_JPEG2K_COMPRESSION_LEVEL 1058
#define IDC_EDIT_H264_BITRATE           1059
#define IDC_EDIT_NUM_SECONDS            1060
#define IDC_EDIT_NTH_SECONDS            1061
#define IDC_TAB_OUTPUT_TYPE             1062
#define IDC_COMBO_VIDEO_RECORD_TYPE     1063
#define IDC_GROUP_MJPEG                 1064
#define IDC_GROUP_H264                  1065
#define IDC_COMBO_IMAGE_RECORD_TYPE     1066
#define IDC_GROUP_PGM_PPM_OPTIONS       1067
#define IDC_CHECK1                      1068
#define IDC_CHECK_PXM_SAVE_AS_BINARY    1068
#define IDC_CHK_CAPTURE_CORRUPT_FRAMES  1068
#define IDC_TURN_ON                     1068
#define IDC_GROUP_JPEG_OPTIONS          1069
#define IDC_CHECK2                      1070
#define IDC_CHECK_JPEG_SAVE_PROGRESSIVE 1070
#define IDC_CHK_SAVE_BAYER_IMAGE        1071
#define IDC_GROUP_TIFF_OPTIONS          1072
#define IDC_COMBO_TIFF_COMPRESSION_METHOD 1073
#define IDC_GROUP_PNG_OPTIONS           1074
#define IDC_CHECK3                      1075
#define IDC_CHECK_PNG_INTERLEAVED       1075
#define IDC_BUTTON_START_STOP_VIDEO_RECORD 1076
#define IDC_GROUP_TIFF_OPTIONS2         1076
#define IDC_BUTTON_BROWSE               1079
#define IDC_STATIC_FRAME_COUNTER        1080
#define IDC_EDIT_NUM_FRAMES             1081
#define IDC_EDIT_NTH_FRAMES             1082
#define IDC_EDIT_NTH_TOTAL_FRAMES       1083
#define IDC_EDIT_NTH_TOTAL_SECONDS      1084
#define IDC_EDIT_SAVE_FILE_PATH         1088
#define IDC_EDIT_MJPEG_COMPRESSION      1089
#define IDC_SPIN_MJPEG_COMPRESSION      1090
#define IDC_SPIN_H264_BITRATE           1091
#define IDC_STATIC_MJPEG_COMPRESSION    1092
#define IDC_STATIC_H264_BITRATE         1093
#define IDC_STATIC_FRAME_RATE           1094
#define IDC_EDIT_FRAME_RATE             1095
#define IDC_STATIC_TIFF_COMPRESSION     1096
#define IDC_STATIC_AVI_SIZE             1096
#define IDC_STATIC_PNG_COMPRESSION      1097
#define IDC_STATIC_AVI_SIZE2            1097
#define IDC_STATIC_JPEG_COMPRESSION     1098
#define IDC_STATIC_SAVE_COUNTER         1099
#define IDC_STATIC_TIFF_COMPRESSION2    1099
#define IDC_COMBO_PNG_COMPRESSION_LEVEL 1100
#define IDC_STATIC_JPEG2K_COMPRESSION_LEVEL 1101
#define IDC_GRP_JPEG2K_OPTIONS          1103
#define IDC_STATIC_BUFFERED_COUNTER     1104
#define IDC_STATIC_AVAILABLE_MEMORY     1106
#define IDC_STATIC_TOTAL_MEMORY         1107
#define IDC_STATIC_MEMORY_LOAD          1108
#define IDC_RADIO_BUFFERED_MODE         1110
#define IDC_RADIO2                      1111
#define IDC_RADIO_STREAMING_MODE        1111
#define IDC_GROUP_BMP_OPTIONS           1114
#define IDC_CHECK_BMP                   1115
#define IDC_CHECK_BMP_8BIT_INDEXED_COLOR 1115
#define IDC_STATIC_STATUS_OUTPUT        1116
#define IDC_STATIC_BUFFERED_MODE_TEXT   1117
#define IDC_STATIC_AVAILABLE_MEMORY_TEXT 1118
#define IDC_STATIC_TOTAL_MEMORY_TEXT    1119
#define IDC_STATIC_CORRUPT_FRAME_COUNTER 1120
#define IDC_STATIC_IMAGE_FORMAT         1121
#define IDC_STATIC_COLOR_PROCESS_MSG    1121
#define IDC_EDIT_THICKNESS              1124
#define IDC_EDIT_LENGTH                 1125
#define IDC_EDIT2                       1127
#define IDC_YOffset                     1127
#define IDC_XOffset                     1128
#define IDC_FILE_SIZE_EDIT              1129
#define IDC_EDIT_FILE_SIZE              1129
#define ID_FILE_STARTIMAGETRANSFER      32771
#define ID_FILE_STOPIMAGETRANSFER       32772
#define ID_CAMERACONTROL_TOGGLECAMERACONTROLDIALOG 32773
#define ID_CAMERACONTROL_TOGGLECAMERACONTROL 32774
#define ID_VIEW_SHOWINFORMATIONPANEL    32775
#define ID_VIEW_DRAWIMAGE               32776
#define ID_VIEW_DRAWCROSSHAIR           32777
#define ID_VIEW_CHANGECROSSHAIRCOLOR    32778
#define ID_HISTGRAM_BTN                 32785
#define ID_VIEW_FULLSCREEN              32786
#define ID_SETTINGS_COLORPROCESSINGALGORITHM 32787
#define ID_COLORPROCESSINGALGORITHM_NONE 32788
#define ID_COLORPROCESSINGALGORITHM_NEARESTNEIGHBOR 32789
#define ID_COLORPROCESSINGALGORITHM_EDGESENSING 32790
#define ID_COLORPROCESSINGALGORITHM_HQLINEAR 32791
#define ID_COLORPROCESSINGALGORITHM_DIRECTIONALFILTER 32792
#define ID_COLORPROCESSINGALGORITHM_RIGOROUS 32793
#define ID_COLORPROCESSINGALGORITHM_IPP 32794
#define ID_VIEW_ENABLEOPENGL            32795
#define ID_ZOOM_IN                      32796
#define ID_VIEW_ZOOMIN                  32797
#define ID_VIEW_ZOOMOUT                 32798
#define ID_ZOOM_OUT                     32801
#define ID_VIEW_STRECHTOFIT             32802
#define ID_VIEW_STRETCHTOFIT            32803
#define ID_HELP_HELP                    32804
#define ID_LAUNCH_HELP                  32805
#define ID_FILE_NEWCAMERA               32814
#define ID_RECORD_BUTTON                32817
#define ID_FILE_GRABAN                  32818
#define ID_FILE_GRAB_AVI                32819
#define ID_VIEW_SHOWHISTOGRAM           32820
#define ID_VIEW_SHOWEVENTSTAT           32822
#define ID_VIEW_EVENTSTAT               32823
#define ID_BUTTON32825                  32825
#define ID_SETTINGS_1                   32826
#define ID_BTN_GETORGSIZE               32827
#define ID_ENABLEOPENGL_GDI             32828
#define ID_ENABLEOPENGL_OPENGL          32829
#define ID_ENABLEOPENGL_DIRECT2D        32830
#define ID_GRAPHICMODE_GDI              32831
#define ID_GRAPHICMODE_OPENGL           32832
#define ID_GRAPHICMODE_DIRECT2D         32833
#define ID_VIEW_SHOWPROPERTYGRID        32834
#define ID_SETTINGS_TOGGLECAMERAPROPERTYGRID 32835
#define ID_SETTINGS_SETXMLPATH          32836
#define ID_BUTTON32837                  32837
#define ID_FILE_PAUSEIMAGETRANSFER      32838
#define ID_VIEW_CHANGECROSSHAIRDIMENSION 32839
#define ID_COLORPROCESSINGALGORITHM_WEIGHTEDDIRECTIONALFILTER 32840

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        177
#define _APS_NEXT_COMMAND_VALUE         32840
#define _APS_NEXT_CONTROL_VALUE         1130
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
